### ISSUE TITLE
Dynamic readout of the settings

### ISSUE THREAD

**Issue by FSharpCSharp** [kine/NVRAppDevOps#30]
So far the path to the settings file/script is hardcoded in the PowerShell function. Wouldn't it be much better to parameterize this path as well or to configure it somewhere? So it would be much easier to use it for other DevOps scenarios without adjustments.

https://github.com/kine/NVRAppDevOps/blob/18d4b74b4e6a295ed11efd0e51d24a33b24fd1de/Read-ALConfiguration.ps1#L17-L21

**Comment by kine** [comment]
Yup, could be, but because long time ago I migrated from ps1 script for settings to json with the settings (place of the json is searched dynamically or could be set through parameters - see [https://dynamicsuser.net/nav/b/kine/posts/navertical-transition-from-settings-ps1-to-json](https://dynamicsuser.net/nav/b/kine/posts/navertical-transition-from-settings-ps1-to-json) ) I recommend to use this way to store the settings.
